# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-18 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import people.helpers
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_auto_20171120_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=people.helpers.PathAndRename('avatar')),
        ),
        migrations.AlterField(
            model_name='person',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Tags', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='image',
            field=models.ImageField(upload_to=people.helpers.PathAndRename('photos')),
        ),
    ]
